version: '2'
services:
  image_t9_ofertas:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: "t9-ofertas"
    ports:
      - "8130:8130"
    environment:
      - JAVA_HEAP_START=256m
      - JAVA_HEAP_MAX=512m
      - JAVA_MAX_MEMORY=724m
      - ENV=local
      - ENVIRONMENT=homologation
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - APP_CLIENT_SECRET=${APP_CLIENT_SECRET}

  redis-master:
    image: bitnami/redis:5.0
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_REPLICATION_MODE: 'master'
    ports:
      - '6379:6379'
  redis-slave1:
    image: bitnami/redis:5.0
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_REPLICATION_MODE: 'slave'
      REDIS_MASTER_HOST: redis-master
    depends_on:
      - redis-master
    ports:
      - '6380:6380'
  redis-slave2:
    image: bitnami/redis:5.0
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_REPLICATION_MODE: 'slave'
      REDIS_MASTER_HOST: redis-master
    depends_on:
      - redis-master
    ports:
      - '6381:6381'
  redis-sentinel:
    image: bitnami/redis-sentinel:5.0
    environment:
      REDIS_MASTER_HOST: redis-master
      REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 10000
    ports:
      - '26379:26379'
