management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
  health:
    circuitbreakers:
      enabled: true
    bulkhead:
      enabled: true
    ratelimiters:
      enabled: true
    db:
      enabled: false
    diskspace:
      enabled: true
