server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka


spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/license/** #localhost:8072/license/v1/organization/d898a142-de44-466c-8c88-9ceb2c2429d3/license
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie #para propagar o token entre os serviços, se não, ele bloqueia



management:
  endpoints:
    web:
      exposure:
        include: "*"